title: Dra. Nadia Arroyo
description: Especialista en Armonización Orofacial y Estética Dental
baseurl: "/Dra.NadiaArroyo" # Para GitHub Pages
url: "https://nadiaarroyo.github.io"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed 